allowBuilds:
  msgpackr-extract: false
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.6
  vite-plus: 0.2.6
minimumReleaseAgeExclude:
  - effect@4.0.0-rc.117
  - "@effect/platform-node-shared@4.0.0-rc.117"
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
